#pragma config(Motor,  motorB,          engineController, tmotorNXT, openLoop, encoder)
#pragma config(Motor,  motorC,          turnerController, tmotorNXT, openLoop, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

const int ENGINE_THRESHOLD = 2;
const int ENGINE_SENSITIVITY = 2;

task main()
{
  nMotorEncoder[engineController] = 0;
  nMotorEncoder[turnerController] = 0;

  for (;;) {
    int engineVal = nMotorEncoder[engineController];
    int turnerVal = nMotorEncoder[turnerController];

    if (abs(engineVal) > ENGINE_THRESHOLD) {
      nMotorEncoderTarget[engineController] = 0;
      motor[engineController] = -engineVal*ENGINE_SENSITIVITY;
    } else {
      engineVal = 0;
      motor[engineController] = 0;
    }

    if (nMotorRunState[engineController] == runStateIdle) {
      motor[engineController] = 0;
    }

    sendMessageWithParm(1, engineVal, turnerVal);

    wait1Msec(100);
  }
}
