#pragma config(Motor,  motorB,          engine,        tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  motorC,          turner,        tmotorNXT, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

const int MAX_TURNER = 200;
const int MAX_TURNER_SPEED = 50;
const int TURNER_THRESHOLD = 10;
const int TURNER_CONTROLLER_SENSITIVITY = 3;
const int ENGINE_CONTROLLER_SENSITIVITY = 1;

int limit(int val, int max) {
  if (val > max) {
    return max;
  } else if (val < -max) {
    return -max;
  } else {
    return val;
  }
}

task main()
{
  nMotorEncoder[turner] = 0;

  for (;;) {
    int nonEmpty = messageParm[0];
    if (nonEmpty == 0) {
      continue;
    }

    int engineBTControl = messageParm[1];
    int turnerBTControl = messageParm[2];
    ClearMessage();

    { // engine engining
      motor[engine] = engineBTControl * ENGINE_CONTROLLER_SENSITIVITY;
    }

    {  // turner turning
      int currTurnerController = limit(turnerBTControl * TURNER_CONTROLLER_SENSITIVITY, MAX_TURNER);
      int currTurner = nMotorEncoder[turner];

      int delta = currTurnerController - currTurner;

      if (abs(delta) > TURNER_THRESHOLD) {
        nMotorEncoderTarget[turner] = currTurnerController;
        motor[turner] = limit(delta, MAX_TURNER_SPEED);
      } else {
        motor[turner] = 0;
      }

      if (nMotorRunState[turner] == runStateIdle) {
        motor[turner] = 0;
      }
    }
  }


}
