#pragma config(Motor,  motorA,          controller,    tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  motorB,          engine,        tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  motorC,          turner,        tmotorNXT, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

const int MAX_TURNER = 350;
const int TURNER_THRESHOLD = 10;
const int TURNER_CONTROLLER_SENSITIVITY = 10;

task main()
{
  nMotorPIDSpeedCtrl[controller] = mtrNoReg;

  int turnerMotor = turner;

  nMotorEncoder[controller] = 0;
  nMotorEncoder[turnerMotor] = 0;

  for (;;) {
    int currController = nMotorEncoder[controller] * TURNER_CONTROLLER_SENSITIVITY;
    int currTurner = nMotorEncoder[turnerMotor];

    if (currController > MAX_TURNER) {
      currController = MAX_TURNER;
    } else if (currController < -MAX_TURNER) {
      currController = -MAX_TURNER;
    }

    int delta = currController - currTurner;

    if (abs(delta) > TURNER_THRESHOLD) {
      nMotorEncoderTarget[turnerMotor] = currController;
      motor[turnerMotor] = delta;
    } else {
      motor[turnerMotor] = 0;
    }

    if (nMotorRunState[turnerMotor] == runStateIdle) {
      motor[turnerMotor] = 0;
    }
  }
}
